name       : mathjax
version    : 3.2.2
release    : 1
source     :
    - https://github.com/mathjax/MathJax/archive/refs/tags/3.2.2.tar.gz : 4206b9645a97f431018d0b6c4021c98607d49ba4dc129f4f2ecce675e2fcba11
homepage   : https://www.mathjax.org/
license    : Apache-2.0
component  : office.scientific
summary    : Beautiful and accessible math in all browsers
description: |
    MathJax is an open-source JavaScript display engine for LaTeX, MathML, and AsciiMath notation that works in all modern browsers. It was designed with the goal of consolidating the recent advances in web technologies into a single, definitive, math-on-the-web platform supporting the major browsers and operating systems. It requires no setup on the part of the user (no plugins to download or software to install), so the page author can write web documents that include mathematics and be confident that users will be able to view it naturally and easily. Simply include MathJax and some mathematics in a web page, and MathJax does the rest.
install    : |
    install -dm00644 $installdir/usr/share/mathjax
    cp -a es5/* $installdir/usr/share/mathjax
